import Head from 'next/head'

import StickersList from 'components/StickersList'

export default function Home() {
  return (
    <div>
      <Head>
        <title>next-starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <StickersList />
    </div>
  )
}
