import Head from 'next/head'
import { ReactElement } from 'react'
import StickersList from 'components/StickersList'

export default function Home (): ReactElement {
  return (
    <div>
      <Head>
        <title>next-starter</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <StickersList />
    </div>
  )
}
